services:
  - type: web
    name: krmu-internship-api
    runtime: node
    rootDir: portal/backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://Shourya:Shourya%401234@cluster0.nbevegk.mongodb.net/internship-portal?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: krmu_internship_super_secret_key_2024
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://summer-internship-chi.vercel.app
